name = "Nullchecker"
uuid = "eea77134-b293-44f2-9248-132e4b7f55c4"
version = "2.0.1-DEV"
authors = ["Matias Klimpel <matias.klimpel@googlemail.com> and contributors"]

[workspace]
projects = ["test"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MaxPlus = "41177cfe-c387-11e9-2806-edd030e4594e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DelimitedFiles = "1.9.1"
LinearAlgebra = "1.10.0, 1.11.0, 1.12.0"
MaxPlus = "0.4.0, 0.5"
Oscar = "1.7.2"
TimerOutputs = "0.5.29"
julia = "1.10.10"
